services:
  web-server-morton-dev:
    image: nginx:latest
    restart: always
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.morton-dev.rule=Host(`${SITE_URL}`)"
      - "traefik.http.routers.morton-dev.entrypoints=websecure"
      - "traefik.http.routers.morton-dev.tls.certresolver=leresolver"

networks:
  proxy:
    external: true
